# Generated by Django 5.2.11 on 2026-06-16 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='carbonrecord',
            index=models.Index(fields=['user', '-created_at'], name='calculator__user_id_253931_idx'),
        ),
    ]
